server:
  port: 8006
  tomcat:
    max-connections: 10000
    accept-count: 200

spring:
  application:
    name: ffjob-report-service8006
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #数据库 #数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ff_job?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '000010'
  mail:
    # 下面这个是QQ邮箱host ， 企业邮箱 : smtp.exmail.qq.com
    host: smtp.qq.com
    # tencent mail port  这个是固定的
    port: 465
    # 你的QQ邮箱
    username: sheep.o5@qq.com
    # 进入邮箱配置后得到的授权码
    password: ixuircqcfimzbdid
    #test-connection: true
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtps

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
info:
  app.name: ffjob-report-service8006 #项目的名称
  company.name: com.yyr #公司的名称

mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    #    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement
  global-config:
    db-config:
      id-type: assign_id
  type-enums-package: com.yyr.pojo
  type-aliases-package: com.yyr.pojo

logging:
#  level:
#    org.springframework.boot.autoconfigure: error
#    root: info
  config: classpath:logback.xml

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  auto-runtime-dialect: true

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000