server:
  port: 7002
spring:
  application:
    name: ffjob-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
zuul:
  prefix: /ff_job # 路由路径前缀
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  SendErrorFilter:
    error:
      disable: true
  routes:
    ffjob-account-service8001: /account/** # 用户微服务的映射路径
    ffjob-bills-service8002: /bills/** # 账单微服务映射路径
    ffjob-finance-service8005: /finance/** #基金与股票微服务
    ffjob-equity-service8004: /equity/** #固定资产与债务
    ffjob-report-service8006: /report/** #报表微服务
    ffjob-common-service8003: /common/**